language: php
matrix:
  fast_finish: true
php:
  - 5.6
  - 5.4
env:
  global:
    - DB=mysqli
  matrix:
    - PHPBB_BRANCH="3.1.x"
    - PHPBB_BRANCH="master"
install:
  - scripts/travis/setup.sh
script:
  - cd phpbb
  - phpBB/vendor/bin/phpunit -c phpBB/ext/s9e/mediaembed/travis/phpunit-$DB-travis.xml --bootstrap ./tests/bootstrap.php